import './Middlepart.css';
import Card from './card/Card'
// import {} from '../middlePart/card/Card'

function Middlepart() {
  return <div className='middlepart'>
      <div className="featuredPools">
          <p>FEATURED POOLS</p>
          <hr/>
          {/* <Card/> */}
          <Card/>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab a modi eos minima magni, quis expedita illum, repellat labore voluptates rem aliquid voluptas inventore animi! Minus eligendi odit quos repellat?
          Temporibus blanditiis pariatur beatae voluptatem ipsam consectetur aspernatur hic consequatur distinctio. Iure atque delectus possimus, sunt blanditiis ratione animi vero ducimus amet veritatis sit tempore? Nostrum ea dolorem tempore eos!
          Magni dolore ex repudiandae rerum! Vero, recusandae quae. Ipsa unde eos sit porro itaque aperiam sed vitae animi, in deserunt harum, odio rem expedita quia, magnam numquam molestiae tempora veniam.
          Vel neque ratione, quia molestiae iste distinctio velit culpa beatae non libero! Quod ea nemo modi ipsam voluptatem aspernatur ab aliquid enim qui. Sint illo mollitia quod veniam dicta quidem!
          Porro quisquam ipsum quibusdam voluptatem enim ullam suscipit placeat, dignissimos corporis labore, eius eligendi et praesentium aspernatur minima numquam aperiam ducimus velit? Dicta facere porro omnis, modi optio atque officia?
          Rem iste dolores architecto ut praesentium nam ipsum. Ut, quibusdam voluptatum necessitatibus rerum mollitia officiis cumque quia id! Mollitia velit quod asperiores dolor suscipit, recusandae minima enim voluptatum. Amet, voluptatibus!
          Rem nobis odio aut voluptates exercitationem id qui libero possimus officia aperiam dolores debitis, excepturi minus nam quae autem rerum eaque. Earum excepturi, incidunt labore non amet quod cum maxime.
          Impedit, saepe nam consequatur aliquam a esse id rerum obcaecati ullam deleniti exercitationem, illum blanditiis voluptate quisquam delectus sint dolorem consequuntur, iure facere labore ex. Quisquam animi officiis delectus reiciendis.
          At id corporis voluptas distinctio odit, quisquam quidem aut eius ratione quia temporibus illum praesentium ullam rerum veniam minima esse tempora molestias culpa porro! Veniam maxime exercitationem eius eum harum!
          Quod fugit odit quae sapiente, ea quam tempora eos qui dicta culpa nostrum aperiam, voluptatibus quasi iusto. Quia possimus cum itaque praesentium. Illo consectetur dolores reprehenderit officiis, itaque maxime aliquam.
          Deserunt ab quidem blanditiis sequi magni dolore. Iste quibusdam quo nobis ullam eaque non, blanditiis dolore quasi animi laborum quos iure eius. Enim, eum placeat! Sint quam aut voluptates dignissimos!
          Assumenda laborum explicabo earum. Repudiandae quisquam dolore soluta repellat debitis iste, atque nam tempore, dignissimos quae ab voluptatum eius obcaecati, perferendis quia voluptate provident. Nostrum quos facilis voluptate sint tenetur!
          Molestiae, natus numquam dignissimos nobis id quod, expedita sint omnis voluptate maiores ratione? Iure vel quod nobis tempora voluptatum natus enim suscipit exercitationem quia deserunt at incidunt, fugiat id harum.
          Veniam quos doloribus eum distinctio repudiandae quasi sunt neque. Architecto, porro distinctio placeat neque explicabo consectetur ipsa facilis laborum aliquam minima at aut est quam rem tempora, harum ipsum nobis?
          Assumenda quas saepe distinctio impedit molestiae dolorem temporibus ad ullam velit adipisci tempora sapiente magnam, minima voluptatibus esse quia placeat voluptatum sed aliquid provident, aspernatur enim? Nisi perferendis quis eos.
          Ipsa numquam aliquid quia officia aliquam, consectetur quidem sit cupiditate reiciendis placeat! Illo, impedit. Eligendi asperiores quidem unde blanditiis nostrum voluptatum perferendis odio sunt iusto voluptatem quasi, nobis quae. Dignissimos?
          Natus magni facilis, impedit similique commodi tempora officiis veniam nam molestias, autem qui debitis perferendis laudantium eligendi at voluptates eius doloremque voluptatem iure. Ut, excepturi ducimus! Optio sunt ducimus possimus!
          Esse accusamus aperiam voluptate iste nemo, sit recusandae illo dolorem fuga sint! Eos modi at libero deleniti hic error iusto saepe labore culpa consequatur officia, corrupti, harum animi voluptate voluptatum.
          Id libero quos nam nisi fugit laboriosam corrupti quo maxime, nesciunt facilis voluptate, molestias excepturi quis. Alias voluptatibus veniam nisi magnam enim, laudantium aspernatur laboriosam amet aperiam provident rem earum?
          Eveniet quam eos iusto laborum dignissimos, sapiente veritatis cum saepe consectetur incidunt molestiae aliquid, animi quasi amet recusandae minus esse quos necessitatibus, praesentium possimus odit perferendis id suscipit alias. Provident!
          Repellat facilis velit, asperiores maxime autem libero ab non voluptates doloribus, sunt dolores corporis ut molestias delectus ea commodi minus dolor pariatur ex eum dignissimos modi accusamus. Quos, beatae nulla.
          Blanditiis culpa saepe ea! Aliquam, quisquam dolore! Quis, molestiae, consequuntur quo a nemo vel fugit laudantium libero, earum amet voluptates labore repudiandae obcaecati ducimus enim sint beatae. Quam, deserunt illum?
          Architecto cupiditate vel iusto temporibus omnis corporis placeat maxime blanditiis enim vitae. Totam culpa esse quis ad dolores quidem! Placeat doloribus similique culpa. Eum ipsam fugiat minus sunt reiciendis dolor!
          Quibusdam perspiciatis incidunt laudantium consequuntur veritatis soluta praesentium harum voluptatibus pariatur sunt, excepturi magni, sapiente dolorem rem voluptates doloribus? Et possimus aliquam consectetur quo inventore, fugit doloribus perspiciatis veritatis commodi?
          Dolore eligendi nemo veritatis eius fugiat, sapiente culpa ipsam illum voluptas vero tempore, ut cumque sequi explicabo odio veniam mollitia accusantium laborum blanditiis libero quam. Ut distinctio doloribus fuga molestias?
          Illum odio, delectus ab incidunt quam, illo sit iure minus soluta repellat corporis cum, quidem distinctio deleniti aliquam placeat pariatur labore animi? Sunt amet, quaerat cum quis praesentium dolor nulla.
          Repudiandae quam ea facilis cupiditate optio dicta inventore impedit excepturi voluptates, pariatur similique omnis ipsam? Doloremque, cum iusto corporis consequatur odit velit ullam aliquam nulla, dolorum temporibus placeat qui consequuntur.
          Suscipit sapiente ratione voluptatem pariatur maiores quis distinctio cum dolores quisquam? Id iusto dolorum quod itaque quidem corrupti asperiores vel ratione laboriosam sequi! Cupiditate laudantium a porro, dolore asperiores sed?
          Qui, blanditiis cupiditate iure assumenda rerum molestias magnam fugiat iste maxime vel fugit quasi animi alias ut. Eum minus quae debitis. Aliquid, corporis error. Quas omnis nemo esse sit? Illo.
          Error non quod delectus ullam repellat maxime totam repudiandae repellendus cum dignissimos eius corrupti expedita, hic eaque cumque illum quos. Autem nesciunt pariatur cupiditate nihil sunt repudiandae porro asperiores veniam!
          Maxime aspernatur possimus sequi? Possimus debitis ratione quod voluptatem ducimus repudiandae omnis, accusantium ipsa numquam, culpa deserunt commodi! Rem omnis delectus similique provident fuga aut pariatur eaque aliquam sapiente ab!
          Cumque sed, excepturi ab possimus repellat quae molestiae deserunt hic tenetur, libero ipsum cum minus mollitia animi illum similique magni odio assumenda quisquam, provident aspernatur pariatur expedita! Asperiores, consequuntur ullam!
          Vitae nam vel dolore aut mollitia molestias, aliquam corrupti accusantium laudantium repudiandae necessitatibus. Quidem recusandae, corrupti quae, ducimus veritatis similique eligendi dignissimos illum id dolor voluptatem ex expedita consequuntur necessitatibus!
          Veniam doloremque beatae quis harum odit expedita atque dicta, culpa aperiam libero voluptatibus iste nulla labore? Maxime, alias nisi, accusamus ducimus velit vero nesciunt fuga iusto natus ratione, debitis ea?
          Dolore, repellendus impedit minima soluta necessitatibus veritatis aspernatur quae facilis neque ex sequi magnam quos molestiae accusamus magni quam nesciunt dignissimos earum laboriosam quisquam veniam architecto culpa! Consequuntur, eum velit!
          Quod odio accusamus aut vero magnam incidunt dolores dicta qui, aspernatur blanditiis esse earum. Earum tenetur quo temporibus? Animi sint impedit cupiditate officia nostrum quos tempora eveniet porro est labore!
          Architecto cumque quos magnam porro assumenda iure, officia atque incidunt provident animi tenetur culpa illum nisi consequatur earum odit fugit optio modi! Recusandae dolorem suscipit maxime facere sit, est sed!
          Incidunt doloribus a nisi, eum cupiditate suscipit quisquam culpa corporis dolorum fuga numquam ad vitae molestias assumenda libero unde reprehenderit repellat! Dignissimos tenetur, rem sint error at sequi dolore illum.
          Culpa corrupti similique quisquam libero dolor quidem maxime. Esse provident recusandae ipsum reiciendis? Vitae perspiciatis quam cupiditate nihil. Unde, veniam minus at a nesciunt delectus fuga voluptate maiores! Aut, vel.
          Ipsa aliquid repellendus facere debitis, voluptatum ex praesentium reiciendis optio laudantium iste minima, possimus, ullam ducimus autem aliquam. Beatae quia, delectus at amet provident ducimus quibusdam ipsam architecto natus? Debitis!
          Deserunt quas aspernatur nemo sed aperiam quasi dolorum assumenda beatae molestias cupiditate ipsam ducimus excepturi, exercitationem eius dolor eos quod perspiciatis sapiente ad nihil. Iste non consequatur soluta cupiditate aspernatur?
          Libero voluptates maxime commodi, reprehenderit enim maiores mollitia perspiciatis delectus esse laborum corrupti perferendis saepe optio sapiente fugiat quia nihil sequi iure quos! Dolorum sapiente, fuga non in magnam delectus.
          Laboriosam cupiditate aspernatur nulla nesciunt ex recusandae deserunt, et alias atque dolorem molestiae, qui accusantium, natus magni maiores nemo rerum blanditiis ullam fugit quis quam corrupti? Et eum veritatis laboriosam.
          Quidem veniam rem dolore ipsa autem deleniti labore magni necessitatibus fugit excepturi ex, sunt iure nulla, magnam enim reiciendis molestiae quas ullam tempore, at mollitia temporibus perferendis! Consequuntur, tempore labore?
          Expedita dignissimos tempora dolores, fuga suscipit accusantium! Temporibus molestiae nihil sed perferendis saepe in necessitatibus, placeat tenetur rerum culpa aliquam accusamus aspernatur, beatae unde optio ex omnis suscipit rem reprehenderit?
          Reiciendis eaque voluptatum harum delectus, nam consequatur est ad explicabo ullam? Quisquam unde sit minima provident dignissimos autem qui reprehenderit odit quae animi, asperiores dolorem libero quis quod recusandae in?
          Saepe provident quam assumenda, ut iure voluptatum velit reprehenderit fuga id eum doloremque, illo doloribus quasi? Ullam modi iusto consequatur quod quisquam nobis delectus, molestiae a in omnis, dignissimos voluptates!
          Expedita perferendis tenetur sequi assumenda amet illo adipisci ipsum fuga culpa deserunt maiores ut perspiciatis eius aspernatur, molestiae, odit quasi placeat. Odit aliquid nobis iste, blanditiis libero harum repellendus vitae.
          Minus repellendus ullam expedita, facere officia eaque impedit rem quidem non unde est ipsa deleniti ut eius. Exercitationem dolore esse, molestias earum deleniti suscipit ea eveniet non nam, sint explicabo.
          Recusandae magni amet veritatis quidem eveniet earum modi itaque blanditiis rem fuga, placeat harum at optio velit voluptatibus sit cum dolorem ut! Officia tempora quia non in dolor! Ducimus, eveniet?
          Suscipit aliquid adipisci minus, eum provident placeat quo tempora culpa natus, assumenda esse totam qui libero excepturi magni fuga repudiandae repellendus et recusandae! Voluptas, praesentium natus. Labore, qui? Aliquid, quod!
          Deleniti asperiores eaque molestias id corporis aspernatur sunt est exercitationem, molestiae labore consequatur itaque natus inventore excepturi quod aliquam? Sit provident similique quaerat veniam voluptas magni voluptate, nisi ducimus tempora.
          Veritatis, deleniti vero, accusamus architecto, recusandae rem at consequatur aperiam eius in earum. Provident corporis maiores vero atque soluta ullam, natus quas nulla quasi, deserunt error voluptas possimus enim. Esse.
          Cum dolor atque quibusdam similique tempore libero vitae ullam. Recusandae commodi eos optio similique inventore. Deleniti quas corporis nemo perferendis nam corrupti, porro et iure omnis dicta optio architecto reiciendis!
          Illo, incidunt odit dicta a, consectetur doloribus dolorem sunt maxime cupiditate odio placeat quis deleniti! Veniam, harum temporibus. Rerum, neque? Officia dolor tempora beatae perspiciatis, tempore adipisci vero error dolore.
          Dolorem, totam asperiores mollitia recusandae ullam, ipsum nisi hic vero vitae esse atque aliquid a soluta cupiditate. Alias modi atque tempora sapiente corporis. Provident ullam, officia molestiae at hic voluptate?
          Mollitia itaque quidem excepturi ut, tenetur animi vero totam repellat, quis perspiciatis natus nemo velit dolores illo illum ipsa voluptatum sint temporibus provident! Explicabo doloribus, eius nisi magnam est deserunt?
          Dicta nostrum ea perspiciatis deserunt ad inventore reprehenderit. Consequatur, ducimus itaque. Cum, inventore deleniti nostrum voluptatibus sed quae iure enim, exercitationem fugit delectus voluptatum quibusdam ad fugiat animi fuga corrupti.
          Doloribus, sunt ipsa error non numquam animi delectus voluptate perferendis, consequatur nemo soluta tempora obcaecati accusamus earum saepe illo, laborum libero commodi ipsam! Voluptas minima fuga, accusantium quisquam dolore consectetur!
          Illum soluta, a, doloremque repellendus nisi saepe aliquam mollitia eveniet ipsa optio hic totam, pariatur quo quos repudiandae blanditiis natus ex id. Adipisci totam laboriosam id autem nesciunt doloribus cupiditate!
          Recusandae maiores nostrum necessitatibus asperiores minima quae voluptatem ipsam corporis esse facere. Esse mollitia, corporis reiciendis quisquam eum, repudiandae quia atque dolores eveniet officia nobis rerum praesentium! Id, est! Nemo!
          Veritatis cupiditate aut fuga nisi voluptatem qui consequuntur doloribus nulla cum praesentium modi fugit at alias vel, tempore perspiciatis similique iusto ea exercitationem minus. Natus atque nemo at. Exercitationem, explicabo?
          Dolorem itaque perspiciatis sapiente natus unde inventore laudantium voluptatum, dignissimos ratione fuga hic. Possimus totam aliquam est nisi sint velit sed, quasi dolore iste eos eveniet quis dignissimos dolorem illum?
          Voluptatibus dolorum molestias odio quas mollitia tempore, voluptates aliquid numquam repellat commodi aspernatur, unde, praesentium velit corrupti? Debitis sint, reiciendis maiores dolor porro tempore consequatur, molestiae incidunt vel aut illo!
          Doloremque id dolorem dolore minus, quos fugiat at? Libero ullam aliquid cupiditate consequatur. Corporis aperiam id repellendus sit ipsam eveniet eaque necessitatibus, consectetur rerum aliquid praesentium, excepturi quas porro dolorem?
          Iure id eaque repudiandae exercitationem temporibus enim suscipit, quibusdam sequi laborum inventore ipsam. Laudantium id repellendus at veniam porro qui, dignissimos placeat. Blanditiis repellendus debitis consequatur cumque libero odit aliquam.
          Rem, mollitia corporis magnam vel eligendi ipsam itaque, repudiandae exercitationem veritatis modi molestiae cupiditate necessitatibus voluptatem? Earum minus consectetur numquam temporibus! Dolorem quisquam a corrupti facere dolorum est blanditiis exercitationem!
          Ipsam autem culpa quis aliquid distinctio porro praesentium, repudiandae harum! Ab harum quaerat labore alias vel enim quia, provident perspiciatis fugiat, ratione dicta ipsum voluptatum laborum molestias nesciunt exercitationem error?
          Tenetur praesentium ullam minima rem nobis sapiente ex aliquid ipsum neque explicabo ipsa suscipit, reprehenderit similique voluptates aliquam pariatur quos officia. Laborum asperiores temporibus dignissimos error iure dolore at magni.
          Laudantium ipsum consequuntur unde, iure earum quas cupiditate repellendus nostrum debitis. Mollitia, in laudantium ab magni, debitis odio et quam excepturi nostrum omnis quod ullam placeat consequatur atque neque aliquid?
          Nisi voluptate sint provident fugiat repudiandae, asperiores nobis, facere fugit quod ad tempora. Vel, natus minus, aperiam eaque dolore cupiditate fugiat odit, doloribus consequuntur ipsam atque sed corrupti rerum nam?
          Soluta officiis voluptatum minima atque dolore debitis et saepe eaque adipisci ipsam illum facere animi expedita dicta porro, voluptatem cupiditate officia nostrum quas unde mollitia sint quo nobis. Perferendis, obcaecati!
          Temporibus possimus adipisci officiis accusamus facilis, voluptatum nostrum laboriosam aliquid ipsam est, consequatur eos suscipit vitae inventore aliquam nesciunt esse modi. Molestiae eaque eligendi repudiandae cupiditate, deleniti minus dolorem maxime?
          Minima doloribus, saepe, libero esse, nobis quis ab dicta laborum voluptatibus nisi quam accusantium tempore. Quod culpa voluptas nulla iusto illo sed velit at rem, corporis fugiat! Quisquam, repellendus rem!
          Officia cum, fugit laudantium inventore nam eveniet in, eaque quaerat itaque vero sunt consectetur magnam labore iusto a nostrum. Aliquid, deleniti nobis exercitationem voluptate quia consectetur numquam sed distinctio ea.
          Cupiditate, natus blanditiis officiis voluptas tenetur amet sequi? A tempore mollitia pariatur voluptatem placeat repellat voluptatum, quaerat sunt facere quod consectetur officia nesciunt ipsum dicta quisquam illo cumque repudiandae nam!
          Incidunt adipisci provident qui, eius quisquam nisi optio architecto quae excepturi, et nesciunt aperiam veritatis dolorem illo error voluptas pariatur sed doloremque. Ab, totam! Alias nam qui mollitia unde amet!
          Voluptatibus minima voluptates eos amet quasi itaque assumenda maxime maiores corrupti perferendis architecto officia consequuntur aspernatur ut, sed porro illo mollitia tempore, enim laborum nobis sint at cumque. Pariatur, exercitationem.
          Rem, sit perspiciatis aspernatur quos pariatur et officiis autem sequi fugit est veritatis maiores quae natus illum debitis ad perferendis molestias nemo ex. Maxime deserunt neque suscipit hic? Accusamus, quasi.
          Corrupti, asperiores! Ex, soluta enim eaque ea minima modi odio laborum amet delectus aut nihil doloribus quos consequuntur quibusdam neque quaerat architecto? Quibusdam eaque est ipsa corrupti, rerum delectus repudiandae?
          Labore incidunt a dolor placeat ipsum consectetur cupiditate repellat sint, assumenda voluptatum temporibus architecto deserunt vitae laborum harum enim, quis dignissimos, asperiores voluptatem nostrum. Hic, sit eius. Error, repellendus distinctio.
          Et nihil nam pariatur optio fugit molestias eius vero voluptatibus odit quisquam consectetur cumque illo accusantium earum, alias sunt debitis temporibus doloribus! Laboriosam doloremque facilis consectetur, voluptas officia eligendi rem.
          Minima soluta fugit quae illo doloribus modi dicta eveniet expedita et? Porro repudiandae nihil hic molestias, dolores, inventore neque cum maxime sint consectetur quae veritatis, deserunt velit architecto. Sint, dolor.
          Dolore alias sequi similique doloremque eveniet ex at possimus tempora pariatur cupiditate nulla nesciunt nam repellat doloribus eligendi, id qui modi, quo corporis deleniti numquam nostrum beatae atque! Illo, hic.
          Sequi reiciendis assumenda, ullam necessitatibus autem vitae nisi reprehenderit nostrum nam laudantium, dolorum voluptates voluptate? Quibusdam numquam nesciunt, culpa alias illo fuga. Molestiae explicabo nulla ipsa vero corrupti eaque a.
          Maiores voluptatem qui omnis nobis hic velit aperiam! Possimus cum quod aperiam neque modi illo laborum ad natus sequi sint omnis ab suscipit, ipsum odio ullam optio repellat blanditiis tenetur?
          Doloribus nostrum libero architecto, iusto debitis enim, blanditiis nisi eveniet nihil atque laudantium? In velit doloremque, recusandae cum, ducimus labore esse iusto maxime iste inventore cumque, iure repellendus laborum incidunt.
          Odio animi provident ipsa vitae dolorum. Repudiandae consequatur atque repellat quo minus! Accusantium eius voluptates numquam illum commodi? Nihil dolorum magni harum atque suscipit repellendus ex aliquid accusantium, nam rem.
          Unde nostrum fugit placeat. Accusantium laudantium doloribus omnis quasi sunt nobis ipsam eum aut quas consectetur est fuga facere odio voluptatem maxime iste totam labore, iure ducimus aperiam recusandae quibusdam.
          Nemo error aliquam alias ipsam autem laborum sit quisquam in ad quam, rem fugiat. Possimus quibusdam, adipisci eligendi, officia rem alias nemo assumenda temporibus eos iusto fuga sapiente voluptate quasi?</p>
      </div>
  </div>;
}

export default Middlepart;
